# Generated by Django 5.2.8 on 2026-03-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_note_image_alter_artist_id_alter_note_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, upload_to='.images/'),
        ),
    ]
