# Generated by Django 5.2.8 on 2026-04-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_alter_artist_id_alter_note_id_alter_show_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
