# Generated by Django 5.2.8 on 2026-04-10 04:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_alter_artist_id_alter_note_id_alter_show_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
