# Generated by Django 5.2.8 on 2026-04-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_alter_artist_id_alter_note_id_alter_show_id_and_more'),
        ('lmn', '0005_alter_note_image'),
    ]

    operations = [
    ]
