# Generated by Django 5.2.8 on 2026-04-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0003_alter_show_end_date'),
        ('lmn', '0006_merge_20260408_1439'),
    ]

    operations = [
    ]
