# Generated by Django 5.2.8 on 2026-04-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0007_merge_20260408_2017'),
        ('lmn', '0007_profile'),
    ]

    operations = [
    ]
