# Generated by Django 5.2.8 on 2026-04-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0006_note_unique_user_show_note'),
        ('lmn', '0007_profile'),
    ]

    operations = [
    ]
