# Generated by Django 5.2.8 on 2026-04-22 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0008_merge_0006_note_unique_user_show_note_0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
