# Generated by Django 5.2.8 on 2026-04-23 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0009_note_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
