# Generated by Django 5.2.8 on 2026-05-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0010_alter_note_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='spam_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('SPAM', 'Spam')], default='PENDING', max_length=10),
        ),
    ]
